
env = SConscript('godot-cpp/SConstruct')

env.Append(CPPPATH='src/')

src = Glob('src/*.cpp')

platform = env['platform']

if (platform == 'linux'):
    libpath = '../libtest{}{}'.format( env['suffix'], env['SHLIBSUFFIX'])
    sharedlib = env.SharedLibrary(libpath, src)
    Default(sharedlib)
